### ISSUE TITLE
Spawning in stuff

### ISSUE THREAD

**Issue by GunsWasTakenVR** [GunsWasTakenVR/Wind64Bypass#2]
Every time you can't spawn any thing in

**Comment by Cart1416** [comment]
wec woom patched it

**Comment by Lollipopwfr** [comment]
rat

















r
a
t
t
e
r
l
m
a
o
u
a
i
n
t

t
r
i
c
k
i
n

n
o
b
o
d
y

**Comment by GunsWasTakenVR** [comment]
I don’t rat lol.
